DATA: ""
LABELS: ""
SAVE: ""
SAVE_PRED: ""
TRAINING: 0.9
EPOCHS: 5

SUBVOL_SHAPE:  [51, 51, 17, 1]
FOV_SHAPE: [33, 33, 11, 1]
KERNEL_SIZE: [3, 3, 3]
NUM_CONV_MODULES: 8
LEARNING_RATE: 0.0001
BATCH_SIZE: 4
CLASSES: [0.0, 0.05, 0.075, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 1]
DELTA: [9, 9, 3]
TMOVE: 0.9
